
# Users

CREATE TABLE `COP4331`.`Users`
(
`ID` INT NOT NULL AUTO_INCREMENT ,
`DateCreated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ,
`DateLastLoggedIn` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ,
`FirstName` VARCHAR(50) NOT NULL DEFAULT "" ,
`LastName` VARCHAR(50) NOT NULL DEFAULT "" ,
`Login` VARCHAR(50) NOT NULL DEFAULT "" UNIQUE ,
`Password` VARCHAR(50) NOT NULL DEFAULT "" ,
PRIMARY KEY (`ID`)
) ENGINE = InnoDB;

# Contacts

CREATE TABLE `COP4331`.`Contacts`
(
`ID` INT NOT NULL AUTO_INCREMENT ,
`Name` VARCHAR(50) NOT NULL DEFAULT "" ,
`Phone` VARCHAR(50) NOT NULL DEFAULT "" ,
`Email` VARCHAR(50) NOT NULL DEFAULT "" ,
`UserID` INT NOT NULL DEFAULT '0' ,
PRIMARY KEY (`ID`)
) ENGINE = InnoDB;